spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/growingduck/config-repo
          username: 462793090@qq.com
          password: 4391615lf
          basedir: D:\project\IdeaProjects\baseDir
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"